# Build Telegraf from source
FROM golang:1.26-alpine as builder

RUN apk add --no-cache git make
WORKDIR /go/src/github.com/influxdata/telegraf
RUN git clone https://github.com/influxdata/telegraf.git . && make

FROM maven:3.8-openjdk-18-slim

RUN apt-get update && \
    apt-get install -y python3-pip jq dos2unix curl netcat nscd p7zip-full && \
    pip3 install awscli

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /go/src/github.com/influxdata/telegraf/telegraf /usr/bin/telegraf

COPY simulation/pom.xml /app
RUN mvn dependency:go-offline

COPY /simulation/src /app/src
RUN mvn install

COPY docker/gatling/entrypoint-gatling.sh /app
RUN dos2unix ./entrypoint-gatling.sh && chmod +x ./entrypoint-gatling.sh

COPY docker/gatling/create-report.sh /app
RUN dos2unix ./create-report.sh && chmod +x ./create-report.sh

COPY docker/gatling/telegraf.conf /etc/telegraf/telegraf.conf
RUN dos2unix /etc/telegraf/telegraf.conf

ENTRYPOINT ["./entrypoint-gatling.sh"]
